_prefs: 
  mapid: ruben.dc87be34
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -98.9857
  - 19.8376
  - 15
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 17
minzoom: 5
name: redvial-bridges-tunel-labels-v2
source: "mapbox:///ruben.c27b3a24,ruben.beb1480d,ruben.b2018778"
styles: 
  - style.mss
template: ''
