_prefs: 
  mapid: ruben.e0d143f6
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -100.3479
  - 19.4275
  - 15
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 5
name: redvial-bridges-styles-v2
source: "mapbox:///ruben.c27b3a24,ruben.2762bf34"
styles: 
  - style.mss
template: ''
